name: FIWARE Coverage Tests

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
        default: "3.10"
      TEST_ENGINE:
        required: false
        type: string
        default: "PYTEST"
      TEST_PATH:
        required: false
        type: string
        default: "tests"
      COVERAGE_TYPE:
        required: false
        type: string
        default: "default"
      EXTRA_REQUIREMENTS:
        required: false
        type: string
        default: ""
      INSTALL_REQUIREMENTS:
        required: false
        type: boolean
        default: true
      USE_UV:
        required: false
        type: boolean
        default: false
      PYTHON_PACKAGE_NAME:
        required: false
        type: string
        default: ""
      TEST_ENV_VARS:
        description: List of env vars, e.g. "['DEBUG=1', 'FOO=bar']"
        required: false
        type: string
        default: '[]'
      FIWARE_DIRECTORY:
        description: Directory containing the docker-compose.yml for FIWARE setup
        required: true
        type: string
      INSTALL_FILIP:
        description: Whether to install FiLiP for testing purposes
        required: false
        type: boolean
        default: false
      FILIP_VERSION:
        description: Version of FiLiP to install
        required: false
        type: string
        default: "0.7.3"

jobs:
  fiware_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup FIWARE Stack
        uses: RWTH-EBC/ci_templates/.github/actions/fiware@main
        with:
          fiware-directory: ${{ inputs.FIWARE_DIRECTORY }}
          healthcheck-urls: >-
            http://localhost:1026/version
            http://localhost:4041/version
          timeout-seconds: 60

      - name: Create env vars for tests
        shell: bash
        run: |
          echo '${{ inputs.TEST_ENV_VARS }}' | jq -r '.[]' >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install Project and Requirements
        uses: RWTH-EBC/ci_templates/.github/actions/install@main
        with:
          use-uv: ${{ inputs.USE_UV }}
          install-requirements: ${{ inputs.INSTALL_REQUIREMENTS }}
          extra-requirements: ${{ inputs.EXTRA_REQUIREMENTS }}

      - name: Install test dependencies
        run: |
          pip install "coverage<7.5.0" "coverage-badge<=1.1.0" pytest setuptools

      - name: Install FiLiP (only for testing purposes)
        if: ${{ inputs.INSTALL_FILIP }}
        run: pip install filip~=${{ inputs.FILIP_VERSION }}

      - name: Run tests with coverage
        run: |
          if [ "${{ inputs.TEST_ENGINE }}" == "PYTEST" ]; then
            coverage run -m pytest ${{ inputs.TEST_PATH }}/
          else
            coverage run -m unittest discover --verbose ${{ inputs.TEST_PATH }}/ "test_*.py"
          fi

      - name: Generate coverage report and badge
        run: |
          mkdir -p coverage
          coverage html -d coverage
          coverage-badge -o coverage/badge.svg

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 1

